
version: '3.8'
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=library_password
    ports:
      - "5432:5432"
  redis:
    image: redis:7-alpine #
    ports:                #
      - "6379:6379"       #
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: book_elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"

  web:
    build: .
    command: >
      sh -c "echo 'Veritabani uyanana kadar 5 saniye bekleniyor...' && sleep 5 &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis #
      - elasticsearch
    environment:
      - PYTHONUNBUFFERED=1

      - DB_NAME=library_db
      - DB_USER=library_user
      - DB_PASSWORD=library_password
      - DB_HOST=db
      - DB_PORT=5432

  celery:
    build: .
    command: celery -A library_api worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
    environment:
      - PYTHONUNBUFFERED=1
      - DB_NAME=library_db
      - DB_USER=library_user
      - DB_PASSWORD=library_password
      - DB_HOST=db
      - DB_PORT=5432

  celery-beat:
    build: .
    command: celery -A library_api beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
      - DB_NAME=library_db
      - DB_USER=library_user
      - DB_PASSWORD=library_password
      - DB_HOST=db
      - DB_PORT=5432


volumes:
  postgres_data:

