# Generated by Django 6.0.2 on 2026-03-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
